apiVersion: v1
kind: Service
metadata:
  labels: {app: helm, name: tiller}
  name: tiller-nodeport
  namespace: kube-system
spec:
  ports:
  - {port: 44134, protocol: TCP}
  selector: {app: helm, name: tiller}
  type: NodePort